# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1i6j4yrf86g42d282mk2r2mxk1is3p9hff8nbxx2my6s4bj1vzss";
    aarch64-linux = "00cbsramlqxmq1wfhk5kwab5p6rs8626wb8vjkarwvwiacm8sbs7";
    x86_64-darwin = "0kr6axflpj2vs00b0bawbbhvxvrgrwz7s8j9wfbsbs43vjaak4fm";
    aarch64-darwin = "1dkmjmnk4x0h7jmwx9c2cc3r62v8pl1051bwjy2kz2jp85cmhrmr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.5/sinq-1.0.0-rc.5-linux-x86_64.tar.gz";
    aarch64-linux = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.5/sinq-1.0.0-rc.5-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.5/sinq-1.0.0-rc.5-macOS-x86_64.tar.gz";
    aarch64-darwin = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.5/sinq-1.0.0-rc.5-macOS-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "sinq";
  version = "1.0.0-rc.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./sinq $out/bin/sinq
  '';

  meta = {
    description = "A concurrent HTTP functional and integration testing tool.";
    homepage = "https://github.com/Veitangie/sinq";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
