# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0zyw3r0hcz136lif3r1r1hczkd4c20fj2yzfxrdv27hp1fr5xjnw";
    aarch64-linux = "1iw7v85dpw4rp2qz2s4pibh08y83y1qn8ynzbbprp2rawmiydww0";
    x86_64-darwin = "1z5k0cd1gypnndy5j6gidrph0mh8gg3400v185z5wn4bjbvmjmq1";
    aarch64-darwin = "1d85w66p3hdk0ddach8w9rikkrjdrxpq2m0mvxwlpn7vhi2x8zg9";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.8/sinq-1.0.0-rc.8-linux-x86_64.tar.gz";
    aarch64-linux = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.8/sinq-1.0.0-rc.8-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.8/sinq-1.0.0-rc.8-macOS-x86_64.tar.gz";
    aarch64-darwin = "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.8/sinq-1.0.0-rc.8-macOS-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "sinq";
  version = "1.0.0-rc.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./sinq $out/bin/sinq
  '';

  meta = {
    description = "A concurrent HTTP functional and integration testing tool.";
    homepage = "https://github.com/Veitangie/sinq";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
